name: Collect Scorecard Data
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 4"
  push:
    paths:
      - 'backend/**'
      - ".github/workflows/collect-workflow-data.yml"
  pull_request:
    paths:
      - 'backend/**'
      - ".github/workflows/collect-workflow-data.yml"

jobs:
  collect_scorecard_data:
    name: Collect Scorecard Data
    runs-on: ubuntu-latest

    steps:
      # Check out codebase
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # Install Poetry
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      # Install project dependencies via Poetry
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      # Run data collection script - Scorecard
      - name: Run Data Collection Script
        env:
          chromedriver_path: "/usr/bin/chromedriver"
        run: poetry run python -m backend.collect_workflow_data
